# Node.js ile React uygulamasını build et
FROM node:16 AS build
WORKDIR /app

# React kaynak kodlarını kopyala ve bağımlılıkları yükle
COPY package.json package-lock.json ./
RUN npm install

# React uygulamasını build et
COPY . .
RUN npm run build

# Nginx ile statik dosyaları serve et
FROM nginx:alpine AS runtime
WORKDIR /usr/share/nginx/html
COPY --from=build /app/build .

# Nginx default.conf ayarları
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
